version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - hyta

  hyta:
    build: .
    env_file:
      - .env
    ports:
      - "4001:4001"
    expose:
      - "4001"
    restart: always

